#version 460 core

layout(local_size_x = 1) in;

struct DrawCommand
{
    uint count;
    uint instanceCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
};

layout(std430, binding = 2) readonly buffer Counter
{
    uint visibleCount;
};

layout(std430, binding = 3) buffer IndirectCommandBuffer
{
    DrawCommand command;
};

void main()
{
    command.instanceCount = visibleCount;
}